version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-node
    steps:
      - checkout # check out the code in the project directory
      - run: node --version
      - run: python --version
      - run: pip --version
      - run: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - run: unzip awscli-bundle.zip
      - run: ./awscli-bundle/install -b ~/bin/aws
      - run: 
          command: |
            echo 'export PATH=/home/circleci/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
      - run: aws --version
      - run: pwd
      - run: ls
      - run: npm i
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - node_modules
  deploy-dev:
    docker:
      - image: circleci/python:3.6.8-node
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: node_modules/.bin/serverless deploy -v -s 'dev' --deploy 'dev' --region ${AWS_DEFAULT_REGION}
          
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
